name: tensorflow
channels:
  - conda-forge 
dependencies:
  - python=3.9   # or 2.7
  - jupyterlab
  - tensorflow
  - matplotlib
  - h5py
  - tensorboard

# conda env update --file environment.yml  --prune